// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"context"
	"fmt"
	"io"
	"strings"

	"github.com/marcodellemarche/nuno/internal/core"
	"github.com/marcodellemarche/nuno/internal/reconcile"
	"github.com/marcodellemarche/nuno/internal/store"
)

// Check outcomes. A warning is something to know; a failure is a precondition
// that is not met, and Nuno will not work as intended until it is.
const (
	statusOK   = "ok"
	statusWarn = "warn"
	statusFail = "fail"
)

type checkResult struct {
	Name   string
	Status string
	Detail string
	// Remedy is the exact command that fixes it. A precondition discovered
	// mid-reconcile is a failure of diagnosis, not of the operator, so every
	// failure carries one (FR-76, ADR-0023).
	Remedy []string
}

// doctor checks every precondition and pairs each failure with the command
// that fixes it. It is what a new operator runs first and what an issue report
// pastes.
//
// With --fix it emits those commands as a script and does not run them. Nuno
// changes per-user quotas and nothing else: reaching occ would mean the Docker
// socket or exec into another container, which buys a one-time setup step with
// root on the host (ADR-0023, ADR-0027, NFR-7).
func doctor(ctx context.Context, a *app, args []string, stdout io.Writer) int {
	emitScript := false
	skipProbe := false
	for _, arg := range args {
		switch arg {
		case "--fix":
			emitScript = true
		case "--skip-probe":
			skipProbe = true
		default:
			fmt.Fprintf(a.stderr, "nuno: unknown option %q\nusage: nuno doctor [--fix] [--skip-probe]\n", arg)
			return ExitConfig
		}
	}

	var checks []checkResult
	checks = append(checks, a.checkConfiguration(ctx)...)
	checks = append(checks, a.checkDatabase(ctx))
	checks = append(checks, a.checkIdentity(ctx))
	checks = append(checks, a.checkProviders(ctx, skipProbe)...)
	checks = append(checks, a.checkLinks(ctx))

	if emitScript {
		writeFixScript(stdout, checks)
		return exitFor(checks)
	}

	writeChecks(stdout, checks)
	return exitFor(checks)
}

func exitFor(checks []checkResult) int {
	for _, c := range checks {
		if c.Status == statusFail {
			// A precondition that is not met is a configuration failure.
			return ExitConfig
		}
	}
	return ExitClean
}

func writeChecks(w io.Writer, checks []checkResult) {
	failures := 0
	for _, c := range checks {
		fmt.Fprintf(w, "[%s] %s\n", strings.ToUpper(c.Status), c.Name)
		if c.Detail != "" {
			fmt.Fprintf(w, "       %s\n", c.Detail)
		}
		for _, line := range c.Remedy {
			fmt.Fprintf(w, "       fix: %s\n", line)
		}
		if c.Status == statusFail {
			failures++
		}
	}
	fmt.Fprintf(w, "\n%d checks, %d failing\n", len(checks), failures)
	if failures > 0 {
		fmt.Fprintln(w, "run `nuno doctor --fix` to get these as a script, and read it before running it")
	}
}

func writeFixScript(w io.Writer, checks []checkResult) {
	fmt.Fprintln(w, "#!/bin/sh")
	fmt.Fprintln(w, "# Generated by nuno doctor --fix. Read it before running it.")
	fmt.Fprintln(w, "#")
	fmt.Fprintln(w, "# Nuno does not run these itself. They reach occ, which would mean the")
	fmt.Fprintln(w, "# Docker socket or exec into another container, and that trades a one-time")
	fmt.Fprintln(w, "# setup step for root on the host. See ADR-0023.")
	fmt.Fprintln(w, "set -eu")

	count := 0
	for _, c := range checks {
		if len(c.Remedy) == 0 || c.Status == statusOK {
			continue
		}
		fmt.Fprintf(w, "\n# %s\n", c.Name)
		if c.Detail != "" {
			for _, line := range strings.Split(wrap(c.Detail, 72), "\n") {
				fmt.Fprintf(w, "# %s\n", line)
			}
		}
		for _, line := range c.Remedy {
			fmt.Fprintln(w, line)
			count++
		}
	}
	if count == 0 {
		fmt.Fprintln(w, "\n# Nothing to fix.")
	}
}

func (a *app) checkConfiguration(ctx context.Context) []checkResult {
	var checks []checkResult

	if len(a.cfg.Providers) == 0 {
		checks = append(checks, checkResult{
			Name:   "providers configured",
			Status: statusFail,
			Detail: "no provider is configured, so there is nothing to observe",
			Remedy: []string{"# set NUNO_PROVIDER_<NAME>_TYPE and NUNO_PROVIDER_<NAME>_URL in .env"},
		})
	} else {
		configured := make([]string, 0, len(a.cfg.Providers))
		for _, p := range a.cfg.Providers {
			configured = append(configured, p.Name+" ("+p.Type+")")
		}
		checks = append(checks, checkResult{
			Name: "providers configured", Status: statusOK,
			Detail: strings.Join(configured, ", "),
		})
	}

	// The three credential types are named distinctly and are never
	// interchangeable (ADR-0022).
	//
	// The key reaches the database only when `nuno serve` bootstraps it, so an
	// offline `nuno doctor` sees an empty table even when NUNO_ADMIN_KEY is
	// set. Reading the environment too is what stops it from telling an
	// operator to set a variable they already set.
	count, err := a.db.CountAdminKeys(ctx)
	switch {
	case err != nil:
		checks = append(checks, checkResult{
			Name: "admin key for the usage API", Status: statusFail, Detail: err.Error(),
		})
	case count > 0:
		checks = append(checks, checkResult{
			Name: "admin key for the usage API", Status: statusOK,
			Detail: fmt.Sprintf("%d usable key(s)", count),
		})
	case !a.cfg.AdminKey.Empty():
		checks = append(checks, checkResult{
			Name: "admin key for the usage API", Status: statusOK,
			Detail: "NUNO_ADMIN_KEY is set; it is stored on the next `nuno serve`",
		})
	default:
		checks = append(checks, checkResult{
			Name:   "admin key for the usage API",
			Status: statusFail,
			Detail: "GET /api/v1/usage refuses every request without one",
			Remedy: []string{"# NUNO_ADMIN_KEY=$(openssl rand -hex 32), then restart nuno"},
		})
	}

	if a.cfg.AdminPassword.Empty() {
		checks = append(checks, checkResult{
			Name:   "admin password for the UI",
			Status: statusWarn,
			Detail: "not set, so the admin surface is only as protected as whatever sits in front of it",
			Remedy: []string{"# NUNO_ADMIN_PASSWORD=... in .env, or put a forward-auth proxy in front"},
		})
	} else {
		checks = append(checks, checkResult{Name: "admin password for the UI", Status: statusOK})
	}

	return checks
}

func (a *app) checkDatabase(ctx context.Context) checkResult {
	if err := store.CheckSchema(ctx, a.db); err != nil {
		return checkResult{
			Name: "database schema", Status: statusFail, Detail: err.Error(),
			Remedy: []string{"nuno migrate"},
		}
	}
	version, err := store.DBVersion(ctx, a.db.R)
	if err != nil {
		return checkResult{Name: "database schema", Status: statusFail, Detail: err.Error()}
	}
	return checkResult{
		Name: "database schema", Status: statusOK,
		Detail: fmt.Sprintf("version %d, backups in %s", version, store.BackupDir(a.db.Path)),
	}
}

func (a *app) checkIdentity(ctx context.Context) checkResult {
	if a.directory == nil {
		return checkResult{
			Name:   "identity source",
			Status: statusWarn,
			Detail: "none configured, so only manual users exist",
			Remedy: []string{"# NUNO_LDAP_URL and NUNO_LDAP_BASE_DN in .env, with a read-only bind user"},
		}
	}

	version, err := a.directory.Version(ctx)
	if err != nil {
		return checkResult{
			Name: "identity source", Status: statusFail,
			Detail: "cannot be read: " + err.Error(),
			Remedy: []string{
				"# check NUNO_LDAP_URL, NUNO_LDAP_BIND_DN and NUNO_LDAP_BIND_PASSWORD",
				fmt.Sprintf("ldapsearch -x -H %s -D '%s' -W -b '%s' -s base",
					core.RedactURL(a.cfg.LDAP.URL), a.cfg.LDAP.BindDN, a.cfg.LDAP.BaseDN),
			},
		}
	}
	detail := "reachable"
	if version != "" {
		detail = version
	}
	return checkResult{Name: "identity source", Status: statusOK, Detail: detail}
}

func (a *app) checkProviders(ctx context.Context, skipProbe bool) []checkResult {
	engine := reconcile.New(a.db, a.log)
	var checks []checkResult

	for _, instance := range a.instances {
		name := instance.Row.Name

		health := instance.Provider.Health(ctx)
		switch {
		case health.Err != nil:
			checks = append(checks, checkResult{
				Name: name + ": reachable and authenticated", Status: statusFail,
				Detail: health.Err.Error(),
				Remedy: remedyForHealth(instance, health),
			})
		case !health.InSupported:
			checks = append(checks, checkResult{
				Name: name + ": version", Status: statusWarn,
				Detail: fmt.Sprintf("%s is outside the major this adapter was verified against, continuing", health.Version),
			})
		default:
			checks = append(checks, checkResult{
				Name: name + ": reachable and authenticated", Status: statusOK, Detail: health.Version,
			})
		}

		checks = append(checks, a.checkCompetingWriters(ctx, engine, instance)...)

		if !skipProbe {
			checks = append(checks, a.checkWriteAccess(ctx, engine, instance))
		}
	}
	return checks
}

func remedyForHealth(instance reconcile.Instance, health core.HealthResult) []string {
	prefix := instance.Row.ConfigRef
	if core.IsAuth(health.Err) {
		return []string{
			"# the credential was rejected: check " + prefix + "_USERNAME, _PASSWORD and _API_KEY",
		}
	}
	if core.IsUnreachable(health.Err) {
		return []string{"# check " + prefix + "_URL and that the container shares a network with the service"}
	}
	return nil
}

func (a *app) checkCompetingWriters(ctx context.Context, engine *reconcile.Engine, instance reconcile.Instance) []checkResult {
	found, undetectable, err := engine.CheckCompetingWriters(ctx, instance)
	if err != nil {
		return []checkResult{{
			Name: instance.Row.Name + ": competing writers", Status: statusWarn,
			Detail: "could not be checked: " + err.Error(),
		}}
	}
	if found == nil && undetectable == nil {
		return nil
	}

	var checks []checkResult
	for _, writer := range found {
		checks = append(checks, checkResult{
			Name:   instance.Row.Name + ": competing writer " + writer.Setting,
			Status: statusFail,
			Detail: writer.Detail + fmt.Sprintf(" (currently %q)", writer.Value),
			Remedy: writer.Remedy,
		})
	}
	if len(found) == 0 {
		checks = append(checks, checkResult{
			Name: instance.Row.Name + ": competing writers", Status: statusOK,
			Detail: "none of the settings this adapter can read are set",
		})
	}

	// The honest half: a setting the API cannot reach is reported as unknown,
	// with the command that shows it, never as absent (ADR-0027).
	for _, writer := range undetectable {
		checks = append(checks, checkResult{
			Name:   instance.Row.Name + ": " + writer.Setting + " cannot be checked from here",
			Status: statusWarn,
			Detail: writer.Detail,
			Remedy: writer.Remedy,
		})
	}
	return checks
}

func (a *app) checkWriteAccess(ctx context.Context, engine *reconcile.Engine, instance reconcile.Instance) checkResult {
	result := engine.ProbeWrite(ctx, instance)
	name := instance.Row.Name + ": credential can write"

	switch {
	case result.Err != nil:
		return checkResult{Name: name, Status: statusFail, Detail: result.Err.Error()}
	case result.Access == core.WriteYes:
		return checkResult{Name: name, Status: statusOK, Detail: result.Detail}
	case result.Access == core.WriteNo:
		return checkResult{
			Name: name, Status: statusFail, Detail: result.Detail,
			Remedy: []string{
				"# on Nextcloud an app password cannot write a quota: use a dedicated admin without 2FA,",
				"# or whitelist this container in allowed_no_password_confirmation_ranges",
				"occ config:system:get allowed_no_password_confirmation_ranges",
			},
		}
	}
	// Unproven is not a failure. It is what a fresh install honestly reports.
	return checkResult{Name: name, Status: statusWarn, Detail: result.Detail}
}

func (a *app) checkLinks(ctx context.Context) checkResult {
	issues, err := a.db.ListLinkIssues(ctx)
	if err != nil {
		return checkResult{Name: "account links", Status: statusFail, Detail: err.Error()}
	}
	if len(issues) == 0 {
		return checkResult{Name: "account links", Status: statusOK, Detail: "nothing unresolved"}
	}

	counts := map[core.LinkIssueKind]int{}
	for _, issue := range issues {
		counts[issue.Kind]++
	}
	var parts []string
	for _, kind := range []core.LinkIssueKind{
		core.IssueAmbiguous, core.IssueStale, core.IssueDangling, core.IssueUnlinked, core.IssueUnmanaged,
	} {
		if counts[kind] > 0 {
			parts = append(parts, fmt.Sprintf("%d %s", counts[kind], kind))
		}
	}

	// Ambiguous, stale and dangling need a decision. Unlinked and unmanaged
	// are facts about the stack, not problems with it.
	status := statusWarn
	if counts[core.IssueAmbiguous]+counts[core.IssueStale]+counts[core.IssueDangling] == 0 {
		status = statusOK
	}
	return checkResult{
		Name: "account links", Status: status, Detail: strings.Join(parts, ", "),
		Remedy: []string{"nuno accounts", "# then `nuno link <uid> <provider> <external-id>` for the ones that need a decision"},
	}
}

// wrap breaks a long detail line for the generated script, where it becomes a
// comment.
func wrap(text string, width int) string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return ""
	}
	var lines []string
	line := words[0]
	for _, word := range words[1:] {
		if len(line)+1+len(word) > width {
			lines = append(lines, line)
			line = word
			continue
		}
		line += " " + word
	}
	return strings.Join(append(lines, line), "\n")
}
